all:
  # DEBUG:1 | INFO:2 | WARNING:4 | ERROR:8 | CRITICAL:16
  debug_logging_level: 31
  normal_logging_level: 28

  DEBUG:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_debug.log
  INFO:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_debug.log
  WARNING:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_error.log
  ERROR:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_error.log
  CRITICAL:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_error.log
  FATAL:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_fatal.log
  HOGE:
    log_file_path: %%CONTEXT_ROOT%%/logs/
    log_file_name: sample_hoge.log
  FLUENTD:
    SOCKET: unix:///var/run/td-agent/td-agent.sock
    # HOST: localhost
    # PORT: 24224
