# only mysql
all:
  common_master:
    host: localhost
    port: 3306
    dbname: sample
    user: sample
    password: sample
    read_only: false
    sharding: false
    persistent: true
  common_slave:
    host: localhost
    port: 3306
    dbname: sample
    user: sample
    password: sample
    read_only: true
    sharding: false
    persistent: true
  shard_user_master:
    sharding: true
    servers:
      shard1_master:
        host: localhost
        port: 3306
        dbname: sample_shard1
        user: sample
        password: sample
        read_only: false
        persistent: true
      shard2_master:
        host: localhost
        port: 3306
        dbname: sample_shard2
        user: sample
        password: sample
        read_only: false
        persistent: true
