all:
  default:
    default_prefix: "SAMPLE_LOCAL_DEF_"
    default_expire: 3600
    server:
      - 
        host: 127.0.11.1
        port: 11211
      - 
        host: localhost
        port: 11211
  api:
    default_prefix: "SAMPLE_LOCAL_API_"
    default_expire: 0
    server:
      - 
        host: 127.0.0.1
        port: 11211
  login:
    default_prefix: "SAMPLE_LOCAL_LOGIN_"
    default_expire: 1800
    server:
      - 
        host: 127.0.0.1
        port: 11211
  resend:
    default_prefix: "SAMPLE_LOCAL_RESEND_"
    default_expire: 600
    server:
      - 
        host: 127.0.0.1
        port: 11211
    
    